export class oilAndGasFacilityMaintenanceProject {
  id: number = 0;
  omL_Name: string = '';
  omL_ID: number = 0;
  companyName: string = '';
  companyemail: string = '';
  year_of_WP: string = '';
  major_Projects: string = '';
  name: string = '';
  objective_Drivers_: string = '';
  approval_License_Permits: string = '';
  capeX_Oversight: string = '';
  budget_Performance: string = '';
  completion_Status: string = '';
  conceptual: string = '';
  feed: string = '';
  detailed_Engineering: string = '';
  construction_Commissioning_: string = '';
  production_Product_Offtakers: string = '';
  challenges: string = '';
  project_Timeline: string = '';
  conformity_Assessment: string = '';
  new_Technology_: string = '';
  has_it_been_adopted_by_DPR_: string = '';
  comment_: string = '';
  planned_ongoing_and_routine_maintenance: string = '';
  actual_capital_expenditure_Current_year_NGN: string = '';
  actual_capital_expenditure_Current_year_USD: string = '';
  proposed_Capital_Expenditure_NGN: string = '';
  proposed_Capital_Expenditure_USD: string = '';
  project_Stage: string = '';
  nigerian_Content_Value: string = '';
  product_Off_takers: string = '';
  actual_Proposed_year: string = '';
  consession_Type: string = '';
  terrain: string = '';
  contract_Type: string = '';
  actual_Proposed: string = '';
  companY_ID: string = '';
  companyNumber: number = 0;
}

export class newTechnologyAndConformityAssessment {
  id: number = 0;
  omL_Name: string = '';
  omL_ID: string = '';
  companyName: string = '';
  companyemail: string = '';
  year_of_WP: string = '';
  name: string = '';
  objective: string = '';
  existing_Alternatives: string = '';
  dpR_Consent: string = '';
  cost: string = '';
  benefits: string = '';
  challenges: string = '';
  timeline: string = '';
  consession_Type: string = '';
  terrain: string = '';
  contract_Type: string = '';
  companY_ID: string = '';
  companyNumber: number = 0;
}

export class facilitiesProjectPerformance {
  id: number = 0;
  omL_Name: string = '';
  omL_ID: string = '';
  companyName: string = '';
  companyemail: string = '';
  year_of_WP: string = '';
  list_of_Projects: string = '';
  planned_completion: string = '';
  actual_completion: string = '';
  contract_Type: string = '';
  terrain: string = '';
  companY_ID: string = '';
  companyNumber: number = 0;

  areThereEvidenceOfDesignSafetyCaseApproval: string = '';
  evidenceOfDesignSafetyCaseApprovalFilename: string = '';
  evidenceOfDesignSafetyCaseApprovalPath: string = '';
  reasonForNoEvidence: string = '';
}
