export enum SBUTABLE {
  //region WORKPROGRAM
  GEOPHYSICAL_ACTIVITIES_ACQUISITIONs = 'GEOPHYSICAL_ACTIVITIES_ACQUISITIONs',
  GEOPHYSICAL_ACTIVITIES_PROCESSINGs = 'GEOPHYSICAL_ACTIVITIES_PROCESSINGs',
  DRILLING_EACH_WELL_COSTs = 'DRILLING_EACH_WELL_COSTs',
  DRILLING_EACH_WELL_COST_PROPOSEDs = 'DRILLING_EACH_WELL_COST_PROPOSEDs',
  DRILLING_OPERATIONS_CATEGORIES_OF_WELLs = 'DRILLING_OPERATIONS_CATEGORIES_OF_WELLs',
  ////////////////////////////
}
